# Array Programming also known as Vectorization

In [1]:
import numpy as np
import math

## What is it?
The fundamental idea behind Array Programming is that operations apply at once to an entire set of values.
This creates a high level overview of the calculations and helps the programmer. It often removes many explicit loops.   

Required when doing advanced calculations.

## Create Test Lists

In [2]:
A = np.array([0,1,2,3,4,5,6,7,8])
B = np.array([8,7,6,5,4,3,2,1,0])

## Example 1: Addition:
Add A and B together adding each corresponding index together.  
Input: A, B  
Expected Output: 
        
         [0,1,2,3,4,5,6,7,8]
        +[8,7,6,5,4,3,2,1,0]
        --------------------
         [8,8,8,8,8,8,8,8,8] <-- Output

### Standard Python

In [4]:
C1 = []
for i in range(len(A)):
    C1.append(A[i] + B[i])
C1

[8, 8, 8, 8, 8, 8, 8, 8, 8]

### Vectorized

In [5]:
C2 = A + B
C2

array([8, 8, 8, 8, 8, 8, 8, 8, 8])

### Result

In [6]:
print("C1", C1)
print("C2", list(C2))

C1 [8, 8, 8, 8, 8, 8, 8, 8, 8]
C2 [8, 8, 8, 8, 8, 8, 8, 8, 8]


### Also works for Subtraction, Division, and Multiplication

In [9]:
A * C1

array([ 0,  8, 16, 24, 32, 40, 48, 56, 64])

### Timing 
Tested before recording  
**Vectorized Time: 6.00e-7 Seconds**  
**Standard Time: 45.70e-7 Seconds**   
The vectorized calculation is 7.616 times faster, and easier to read once learned. 

## Example 2: Scaler Matrix Multiplication
Multiply each value in A by 4.
Input: A, B  
Expected Output: 
        
         [0,1,2,3,4,5,6,7,8]
        *                 4
        --------------------
    [0,4,8,12,16,20,24,28,32] <-- Output

In [10]:
A = np.array([0,1,2,3,4,5,6,7,8])

### Standard Python

In [11]:
B1 = []
for n in A:
    B1.append(n * 4)
B1

[0, 4, 8, 12, 16, 20, 24, 28, 32]

### Vectorized

In [13]:
B2 = A * 4
B2

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32])

### Result

In [14]:
print(B1)
print(list(B2)) ## Originally a numpy array

[0, 4, 8, 12, 16, 20, 24, 28, 32]
[0, 4, 8, 12, 16, 20, 24, 28, 32]


### Timing
Vectorized: **8.44e-7 Seconds**   
Standard: **40.8e-7 Seconds**

## Example 3: Euclidean Distance  
![/Euclidean Distance](./images/euclidean_distance.jpg)

Formula:   

        distance = sqrt(
                       + (x1 - x2)^2
                       + (y1 - y2)^2 
                       + (z1 - z2)^2 
                       + ... )
        
        
Can be used to calculate the straight line distance between two points:  
Point 1: (0,0)  
Point 2: (5, 5)

        distance = sqrt( (0 - 5)^2 + (0 - 5)^2 )  
        distance = sqrt(50) = 7.0710678118654755


In [22]:
A = np.array([0,1,2,3,4])
B = np.array([8,7,6,5,4])

A = np.arange(100).reshape((10,10))
B = np.arange(100).reshape((10,10))[::-1]

### Standard Python


In [23]:
running_sum = 0

for i in range(len(A)):
    difference = A[i] - B[i]
    power = difference ** 2
    running_sum += power
    
dist1 = math.sqrt(running_sum)
dist1

TypeError: only size-1 arrays can be converted to Python scalars

### Vectorized

In [24]:
# diff = A - B
# power = diff ** 2
# summation = np.sum(power)
# dist2 = np.sqrt(summation)

dist2 = np.sqrt(np.sum((A - B) ** 2))

In [25]:
print("Standard Method", dist1)
print("Vectorized Method", dist2)

Standard Method 10.954451150103322
Vectorized Method 574.4562646538029
