# Numpy Slicing

In [8]:
import numpy as np

# Syntax

### One dimensional Array
    array[index]
Same as python list slicing

In [2]:
A = np.array([0,1,2,3,4,5])
A

array([0, 1, 2, 3, 4, 5])

In [3]:
A[0] 

0

In [4]:
A[3] 

3

#### Slicing multiple items
    array[start_index:finish_index]
From index 1 inclusive to final index exclusive (does not include final value)

In [5]:
A[0:3] 

array([0, 1, 2])

In [6]:
A[1:]

array([1, 2, 3, 4, 5])

In [7]:
A[:] 

array([0, 1, 2, 3, 4, 5])

In [ ]:
A[-1] 

In [ ]:
A[-2:] 

In [ ]:
A[:-1] 

### Two Dimensional Arrays
    array[row-start-index : row-end-index, col-start-index : col-end-index]
Similar to normal Python slicing with additional features

In [ ]:
B = np.array([[0, 1, 2, 3], 
              [4, 5, 6, 7], 
              [8, 9, 10,11], 
              [12,13,14,15]])

#### Standard Python Syntax

In [ ]:
B[0][1] 

#### Numpy Syntax

In [ ]:
B[0,1]  

In [ ]:
B[0] 

In [ ]:
B[0:2] 

## What if we want first two columns?
#### Normal Python Syntax

In [ ]:
B = np.array([[0, 1, 2, 3], 
              [4, 5, 6, 7], 
              [8, 9, 10,11], 
              [12,13,14,15]])

## Final List
columns_0_1 = []

## Iterates over all rows
for i in range(B.shape[0]):
    ## Holds the column before adding into final array
    temp_column = []
    
    ## Iterates over each row, j, from 0 to 2
    for j in range(0, 2):
        ## Adds item to column j
        temp_column.append(B[i, j])
    
    ## Adds column to list of columns
    columns_0_1.append(temp_column)
    
## Outputs Results
np.array(columns_0_1)

#### Numpy Syntax

In [ ]:
## Numpy Syntax
columns = B[:, :2] ## Gets columns
columns

# Problem 1
Given a 2D numpy array A with shape (4,4). Using one slice retrieve the center 4 items.  
Example:  
Input  

    [[0, 1, 2, 3], 
     [4, 5, 6, 7], 
     [8, 9, 10,11], 
     [12,13,14,15]]
Output

    [[5,6],
     [9,10]]

In [9]:
A = np.array([[0, 1, 2, 3], 
              [4, 5, 6, 7], 
              [8, 9, 10,11], 
              [12,13,14,15]])
rows = A[1:3]
columns = A[:, 1:3]
answer = A[1:3, 1:3]
answer

array([[ 5,  6],
       [ 9, 10]])

In [10]:
"Test Case 1: " + str((answer == np.array([[5,6],[9,10]])).all())

'Test Case 1: True'

## Bonus Problem
Given a 4D numpy array with shape (4,4,4,4). Using one slice retrieve the center 2 by 2 by 2 by 2 items.


In [ ]:
## Starting Array
A = np.arange(4**4).reshape((4,4,4,4))

In [ ]:
result = ...

In [ ]:
result