# Numpy Sum Method

In [1]:
import numpy as np

## Syntax

In [2]:
array = np.array([0,1,2,3,4,5])
array.sum()
# OR
np.sum(array)

15

### Optional Parameter: axis

In [3]:
array_2d = np.array([[1,1,1], 
                     [1,1,1]])
## Axis 0 is for columns
array_2d.sum(axis=0)

array([2, 2, 2])

In [4]:
## Axis 1 is for rows
array_2d.sum(axis=1)

array([3, 3])

Axis 2 and beyone continue the pattern

## Problem 1
Given a numpy array A with shape (2,4). Calculate the sum of all elements in the array. 

In [8]:
A = np.array([[1,2,3,4],
              [4,3,2,1]])

In [9]:
answer = A.sum()
answer

20

## Problem 2
Given numpy array B with shape (2,4). Calculate the sum for every column.

In [10]:
B = np.array([[1,2,3,4],
              [4,3,2,1]])

In [11]:
answer = B.sum(axis=0)

answer

array([5, 5, 5, 5])